### ISSUE TITLE
Uncaught TypeError: entry.getPath is not a function

### ISSUE THREAD

**Issue by garex** [rjaviervega/tree-view-git-modified#10]
# Stack

```
/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:788
Hide Stack Trace
TypeError: entry.getPath is not a function
    at TreeView.module.exports.TreeView.moveSelectedEntry (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:788:25)
    at space-pen-div.atom.commands.add.tree-view:move (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:292:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by garex** [comment]
# Conditions

* tree-view-git-modified is enabled (on disabling this bug was gone)
* we have two newly added files (not staged) that have names like `090-gitolite-050-setup` and `090-gitolite-050-setup-first-time`
* bug repeats only when renaming by keyboard "F2"
