### ISSUE TITLE
Failed to activate the tree-view-git-modified package

### ISSUE THREAD

**Issue by shoesel** [rjaviervega/tree-view-git-modified#14]
1. Add a project folder that is not a git project
2. Enable the "tree-view-git-modified" package
-> Atom-Error notification shown

OR
1. Have the "tree-view-git-modified" package enabled
2. Add a project folder that is not a git project
-> Nothing happens, folder not added

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [tree-view-git-modified](https://github.com/rjaviervega/tree-view-git-modified) package, v0.6.4

### Stack Trace

Failed to activate the tree-view-git-modified package

```
At Cannot read property 'path' of null

TypeError: Cannot read property 'path' of null
    at /Users/XXXXX/.atom/packages/tree-view-git-modified/lib/tree-view-git-modified-view.coffee:29:18
    at TreeViewGitModifiedView.module.exports.TreeViewGitModifiedView.loadRepos (/Users/XXXXX/.atom/packages/tree-view-git-modified/lib/tree-view-git-modified-view.coffee:28:9)
    at new TreeViewGitModifiedView (/Users/XXXXX/.atom/packages/tree-view-git-modified/lib/tree-view-git-modified-view.coffee:14:6)
    at Object.module.exports.TreeViewGitModified.activate (/Users/XXXXX/.atom/packages/tree-view-git-modified/lib/tree-view-git-modified.coffee:12:36)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:328:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -3:25.4.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -3:22.5.0 editor:consolidate-selections (atom-text-editor.editor.power-mode.is-focused)
     -3:22.5.0 core:cancel (atom-text-editor.editor.power-mode.is-focused)
     -3:19.8.0 clipboard-history:copy (atom-text-editor.editor.power-mode.is-focused)
     -3:03.4.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -3:02.9.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -3:01.0 editor:move-to-first-character-of-line (atom-text-editor.editor.power-mode.is-focused)
     -2:58.8.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -2:58 editor:move-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
 19x -2:57.6.0 core:delete (atom-text-editor.editor.power-mode.is-focused)
 18x -2:53.9.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
  3x -2:48.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:41.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.power-mode.is-focused)
     -2:38.3.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:30.3.0 window:save-all (atom-text-editor.editor.power-mode.is-focused)
     -0:41.2.0 tabs:close-all-tabs (li.texteditor.tab.sortable.active.right-clicked)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "editorconfig",
      "atom-numbers",
      "atom-sort-sass",
      "active-files",
      "compare-files",
      "atom-ternjs",
      "tree-view-git-status",
      "open-on-github",
      "git-time-machine",
      "merge-conflicts"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
angularjs, v0.3.4
clip-history, v0.2.1
clipboard-history, v0.6.6
cursor-history, v0.5.9
file-bookmark, v0.3.1
file-icons, v1.7.14
highlight-selected, v0.11.2
language-babel, v2.28.0
language-gherkin, v1.0.4
linter, v1.11.10
linter-eslint, v7.2.2
linter-htmlhint, v1.2.0
linter-sass-lint, v1.5.0
minimap, v4.24.6
minimap-git-diff, v4.3.1
pigments, v0.29.2
pretty-json, v1.4.1
project-view, v0.5.0
svg-preview, v0.7.4
tree-view-git-modified, v0.6.4
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Comment by menting311** [comment]
Here is the section of code that is causing this. I am not sure how this would ever work...how can you get the repo.path if you already know the repo is null?

I just commented out lines 28-30. Does that create any additional issues? I have not noticed any yet.

USER\.atom\packages\tree-view-git-modified\lib\tree-view-git-modified-view.coffee
Starting with line 27

if repo == null
        for tree in self.treeViewGitModifiedPaneViewArray
          if repo.path == tree.repo.path
            tree.show()

**Comment by menting311** [comment]
Also, Removing all project folders and restarting, then re-adding projects does not fix this. One it happens it appears to keep happening...

**Comment by phumke** [comment]
Is there a resolution on this?  I've found that the list of changed files isn't showing up for my projects anymore.  I tried removing the project folder and readding it, and uninstalling and reinstalling without any luck.
