### ISSUE TITLE
Uncaught TypeError: _ref.is is not a function

### ISSUE THREAD

**Issue by thibaudgg** [rjaviervega/tree-view-git-modified#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view-git-modified](https://github.com/rjaviervega/tree-view-git-modified) package 0.7.1

### Stack Trace

Uncaught TypeError: _ref.is is not a function

```
At /Users/Thibaud/.atom/packages/tree-view-git-modified/lib/tree-view-git-modified.coffee:35

TypeError: _ref.is is not a function
    at /packages/tree-view-git-modified/lib/tree-view-git-modified.coffee:35:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:46.7.0 core:backspace (input.hidden-input)
     -2:43.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:42.2.0 core:save (input.hidden-input)
     -2:41.7.0 ruby-test:test-previous (input.hidden-input)
     -1:00.0 core:save (input.hidden-input)
     -0:58.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:57.7.0 core:confirm (input.hidden-input)
  3x -0:55.3.0 ruby-test:test-single (input.hidden-input)
     -0:13.4.0 tree-view:toggle (input.hidden-input)
     -0:12.3.0 editor:consolidate-selections (input.hidden-input)
     -0:12.3.0 core:cancel (input.hidden-input)
     -0:12.1.0 editor:consolidate-selections (input.hidden-input)
     -0:12.1.0 core:cancel (input.hidden-input)
     -0:12.1.0 editor:consolidate-selections (input.hidden-input)
     -0:12.1.0 core:cancel (input.hidden-input)
     -0:08.1.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.0.0 
atom-test-runner 0.11.1 
busy-signal 1.3.0 
disable-arrow-keys 0.1.0 
emacs-core-keys 0.2.3 
file-icons 2.1.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-fish-shell 1.0.5 
language-mjml 1.9.0 
language-rspec 0.6.1 
language-tmux 0.4.0 
linter 2.1.2 
linter-jshint 3.0.3 
linter-rubocop 2.0.0 
linter-ruby 1.2.5 
linter-stylelint 3.10.0 
linter-ui-default 1.2.2 
maximize-panes 0.2.0 
move-panes 0.2.0 
rails-rspec 0.3.2 
railscasts-syntax 0.5.0 
rspec-toggle-focus 0.3.0 
ruby-block-converter 3.5.0 
ruby-slim 0.2.0 
ruby-test 1.0.1 
script 3.14.1 
toggle-quotes 1.0.1 
tree-view-git-modified 0.7.1 
```

**Comment by rjaviervega** [comment]
This issues has been fixed on v0.7.2.
